*---------------------------------------------------------------------*
*    generated viewmaintenance function pool
*   generation date: 15.06.2010 at 13:31:40 by user IBMABAP01
*   view maintenance generator version: #001407#
*---------------------------------------------------------------------*
*******************************************************************
*   System-defined Include-files.                                 *
*******************************************************************
  INCLUDE LZ6MM_RGPNRGPTOP.                  " Global Data
  INCLUDE LZ6MM_RGPNRGPUXX.                  " Function Modules

*******************************************************************
*   include-files generated by view maintenance tool              *
*******************************************************************

*      view related include-files   (never change, please)        *
  INCLUDE LZ6MM_RGPNRGPF00                        . " subprograms
  INCLUDE LZ6MM_RGPNRGPI00                        . " PAI modules

*      general include-files        (never change, please)        *
  INCLUDE LSVIMFXX                                . " subprograms
  INCLUDE LSVIMOXX                                . " PBO modules
  INCLUDE LSVIMIXX                                . " PAI modules

*******************************************************************
*   User-defined Include-files (if necessary).                    *
*******************************************************************
* INCLUDE LZ6MM_RGPNRGPF...                  " Subprograms
* INCLUDE LZ6MM_RGPNRGPO...                  " PBO-Modules
* INCLUDE LZ6MM_RGPNRGPI...                  " PAI-Modules
