*---------------------------------------------------------------------*
*    generated viewmaintenance function pool
*   generation date: 25.06.2011 at 11:11:10 by user IBMABAP01
*   view maintenance generator version: #001407#
*---------------------------------------------------------------------*
*******************************************************************
*   System-defined Include-files.                                 *
*******************************************************************
  INCLUDE LZ6MM_TAX_CODETOP.                 " Global Data
  INCLUDE LZ6MM_TAX_CODEUXX.                 " Function Modules

*******************************************************************
*   include-files generated by view maintenance tool              *
*******************************************************************

*      view related include-files   (never change, please)        *
  INCLUDE LZ6MM_TAX_CODEF00                       . " subprograms
  INCLUDE LZ6MM_TAX_CODEI00                       . " PAI modules

*      general include-files        (never change, please)        *
  INCLUDE LSVIMFXX                                . " subprograms
  INCLUDE LSVIMOXX                                . " PBO modules
  INCLUDE LSVIMIXX                                . " PAI modules

*******************************************************************
*   User-defined Include-files (if necessary).                    *
*******************************************************************
* INCLUDE LZ6MM_TAX_CODEF...                 " Subprograms
* INCLUDE LZ6MM_TAX_CODEO...                 " PBO-Modules
* INCLUDE LZ6MM_TAX_CODEI...                 " PAI-Modules
