*&---------------------------------------------------------------------*
*& Report  ZMM_HO_DISP_REG_DATA
*&
*&---------------------------------------------------------------------*
*&
*&
*&---------------------------------------------------------------------*

REPORT  ZMM_HO_DISP_REG_DATA.


*&*******************************************************************************************&
*&                             DATA DECLARATIONS                                            &
*&*******************************************************************************************&

TYPE-POOLS SLIS.

DATA : A TYPE ZMIS_SALES_DATA-VKORG,
       B TYPE ZMIS_SALES_DATA-VTWEG,
       C TYPE ZMIS_SALES_DATA-SPART,
       D TYPE ZMIS_SALES_DATA-BZIRK,
       E TYPE ZMIS_SALES_DATA-ZMONTH,
       F TYPE ZMIS_SALES_DATA-ZYEAR,
       G TYPE ZMIS_SALES_DATA-WERKS.

 DATA : WA_FINAL TYPE ZSD_REG_SALE_FC ,
        IT_FINAL LIKE TABLE OF WA_FINAL,

        IT_FCAT  TYPE SLIS_T_FIELDCAT_ALV,                          "SLIS_T_FIELDCAT_ALV
        WA_FCAT  LIKE LINE OF IT_FCAT.


 DATA : IT_MNAMES LIKE TABLE OF T247,
        WA_MNAMES LIKE T247.

DATA :  MONTH1  TYPE DATUM,
        MONTH2  TYPE DATUM,
        MONTH3  TYPE DATUM.

DATA : M1_NAME(10) TYPE C,
       M2_NAME(10) TYPE C,
       M3_NAME(10) TYPE C,

       Y1M1NAME(10) TYPE C,
       Y1M2NAME(10) TYPE C,
       Y1M3NAME(10) TYPE C,

       Y2M1NAME(10) TYPE C,
       Y2M2NAME(10) TYPE C,
       Y2M3NAME(10) TYPE C,

       Y3M1NAME(10) TYPE C,
       Y3M2NAME(10) TYPE C,
       Y3M3NAME(10) TYPE C,

       YEAR1(5) TYPE  C,
       YEAR2(5) TYPE  C,
       YEAR3(5) TYPE  C.

       DATA R TYPE CHAR01.

*&*******************************************************************************************&
*&                             SELECTION SCREEN                                              &
*&*******************************************************************************************&

SELECTION-SCREEN BEGIN OF BLOCK A WITH FRAME.
SELECTION-SCREEN BEGIN OF BLOCK B WITH FRAME TITLE TEXT-001.

SELECT-OPTIONS : SO_VKORG  FOR A MODIF ID  PK  DEFAULT 1000,                           " SALES ORGAN
                 SO_VTWEG  FOR B MODIF ID  PK  DEFAULT 10,                             " DIST CHANNEL
                 SO_SPART  FOR C MODIF ID  PK  DEFAULT 10,                             " DIVISION
                 SO_BZIRK  FOR D MODIF ID  PK ,                                        " REGION
                 SO_WERKS  FOR G MODIF ID  PK,                                         " PLANT
                 SO_ZMONT  FOR E MODIF ID  PK1 DEFAULT SY-DATUM+4(2)
                                               NO INTERVALS NO-EXTENSION OBLIGATORY,   " MONTH
                 SO_ZYEAR  FOR F MODIF ID  PK1 DEFAULT SY-DATUM+0(4) OBLIGATORY
                                               NO INTERVALS NO-EXTENSION.              " YEAR


SELECTION-SCREEN END OF BLOCK B.
SELECTION-SCREEN END OF BLOCK A.


*---------------------------------------------------------------------" START OF SELECTION

START-OF-SELECTION.
*---------------------------------------------------------------------" MONTH NAMES FOR DYNAMIC COLUMN HEADINGS
SELECT * FROM T247 INTO TABLE IT_MNAMES WHERE SPRAS EQ 'EN'.

*MONTH1 = SY-DATUM.
*MONTH2 = MONTH1 + 1.
*MONTH3 = MONTH1 + 2.

CONCATENATE SO_ZYEAR-LOW SO_ZMONT-LOW '01' INTO MONTH1.

DATA DURATION TYPE PSEN_DURATION.

DURATION-DURMM = 1.

CALL FUNCTION 'HR_99S_DATE_ADD_SUB_DURATION'
  EXPORTING
    im_date           = MONTH1
    im_operator       = '+'
    im_duration       = DURATION
 IMPORTING
   EX_DATE            = MONTH2.

DURATION-DURMM  = DURATION-DURMM  + 1.

CALL FUNCTION 'HR_99S_DATE_ADD_SUB_DURATION'
  EXPORTING
    im_date           = MONTH1
    im_operator       = '+'
    im_duration       = DURATION
 IMPORTING
   EX_DATE            = MONTH3.


IF IT_MNAMES IS NOT INITIAL.
SORT IT_MNAMES BY MNR.
READ TABLE  IT_MNAMES INTO WA_MNAMES WITH KEY MNR = MONTH1+4(2) BINARY SEARCH.
CONCATENATE WA_MNAMES-KTX  '`' MONTH1+0(4) INTO M1_NAME.
READ TABLE  IT_MNAMES INTO WA_MNAMES WITH KEY MNR = MONTH2+4(2) BINARY SEARCH.
CONCATENATE WA_MNAMES-KTX  '`' MONTH2+0(4) INTO M2_NAME.
READ TABLE  IT_MNAMES INTO WA_MNAMES WITH KEY MNR = MONTH3+4(2) BINARY SEARCH.
CONCATENATE WA_MNAMES-KTX  '`' MONTH3+0(4) INTO M3_NAME.
ENDIF.


YEAR1 = MONTH1+0(4) - 1.
YEAR2 = MONTH2+0(4) - 1 .
YEAR3 = MONTH3+0(4) - 1.

CONCATENATE  M1_NAME+0(3) '`' YEAR1 INTO Y1M1NAME.
CONCATENATE  M2_NAME+0(3) '`' YEAR2 INTO Y1M2NAME.
CONCATENATE  M3_NAME+0(3) '`' YEAR3 INTO Y1M3NAME.

YEAR1 = YEAR1 - 1.
YEAR2 = YEAR2 - 1.
YEAR3 = YEAR3 - 1.
CONCATENATE  M1_NAME+0(3) '`' YEAR1 INTO Y2M1NAME.
CONCATENATE  M2_NAME+0(3) '`' YEAR2 INTO Y2M2NAME.
CONCATENATE  M3_NAME+0(3) '`' YEAR3 INTO Y2M3NAME.

YEAR1 = YEAR1 - 1.
YEAR2 = YEAR2 - 1.
YEAR3 = YEAR3 - 1.
CONCATENATE  M1_NAME+0(3) '`' YEAR1 INTO Y3M1NAME.
CONCATENATE  M2_NAME+0(3) '`' YEAR2 INTO Y3M2NAME.
CONCATENATE  M3_NAME+0(3) '`' YEAR3 INTO Y3M3NAME.

*---------------------------------------------------------------------" FETCH DATA

SELECT * FROM ZSD_REG_SALE_FC INTO TABLE IT_FINAL WHERE VKORG  IN SO_VKORG
                                                  AND   VTWEG  IN SO_VTWEG
                                                  AND   SPART  IN SO_SPART
                                                  AND   BZIRK  IN SO_BZIRK
                                                  AND   ZMONTH IN SO_ZMONT
                                                  AND   ZYEAR  IN SO_ZYEAR
                                                  AND   WERKS  IN SO_WERKS.

*---------------------------------------------------------------------" AUTHORIZATION CHECK
*PERFORM AUTHORIZATION_CHECK.

*---------------------------------------------------------------------" FILL FIELDCATALOG
PERFORM FCAT.

*---------------------------------------------------------------------" DISPLAY GRID ALV

IF IT_FINAL IS NOT INITIAL.

CALL FUNCTION 'REUSE_ALV_GRID_DISPLAY'
  EXPORTING
    I_CALLBACK_PROGRAM                = SY-REPID
    IT_FIELDCAT                       = IT_FCAT
    I_SAVE                            = 'X'
    I_CALLBACK_USER_COMMAND           = 'USER_COMMAND'
     TABLES
    T_OUTTAB                          = IT_FINAL
 EXCEPTIONS
   PROGRAM_ERROR                     = 1
   OTHERS                            = 2  .
IF SY-SUBRC <> 0.
 MESSAGE ID SY-MSGID TYPE SY-MSGTY NUMBER SY-MSGNO
         WITH SY-MSGV1 SY-MSGV2 SY-MSGV3 SY-MSGV4.
ENDIF.

ELSE.

*IF R = 1.
*MESSAGE 'YOU ARE NOT AUTHORIZED' TYPE 'S' DISPLAY LIKE 'W'.
*ELSE.
MESSAGE 'DATA NOT FOUND' TYPE 'S' DISPLAY LIKE 'E'.
*ENDIF.


ENDIF.

*&*******************************************************************************************&
*&                             SUB ROUTINES                                                  &
*&*******************************************************************************************&

FORM AUTHORIZATION_CHECK.

LOOP AT IT_FINAL INTO WA_FINAL.

 AUTHORITY-CHECK OBJECT 'V_VBAK_VKO'
                     ID 'ACTVT' FIELD '03'
                     ID 'VKORG' FIELD WA_FINAL-VKORG
                     ID 'VTWEG' FIELD WA_FINAL-VTWEG
                     ID 'SPART' FIELD WA_FINAL-SPART.

  IF SY-SUBRC NE 0.
   DELETE IT_FINAL FROM WA_FINAL.
   R = 1.
  ENDIF.

  AUTHORITY-CHECK OBJECT 'Z_SALESD'
                     ID  'ACTVT' FIELD '03'
                     ID  'BZIRK' FIELD WA_FINAL-BZIRK..

  IF SY-SUBRC NE 0.
   DELETE IT_FINAL FROM WA_FINAL.
   R = 1.
  ENDIF.

  CLEAR WA_FINAL.

ENDLOOP.
ENDFORM.

FORM FCAT.

WA_FCAT-FIELDNAME = 'ZMONTH'.
WA_FCAT-TABNAME   = 'IT_FINAL'.
WA_FCAT-SELTEXT_M = 'MONTH'.
WA_FCAT-OUTPUTLEN = '8'.
APPEND WA_FCAT TO IT_FCAT.
CLEAR WA_FCAT.

WA_FCAT-FIELDNAME = 'ZYEAR'.
WA_FCAT-TABNAME   = 'IT_FINAL'.
WA_FCAT-SELTEXT_M = 'YEAR'.
WA_FCAT-OUTPUTLEN = '8'.
APPEND WA_FCAT TO IT_FCAT.
CLEAR WA_FCAT.


WA_FCAT-FIELDNAME = 'VKORG'.
WA_FCAT-TABNAME   = 'IT_FINAL'.
WA_FCAT-SELTEXT_M = 'SALES ORG'.
APPEND WA_FCAT TO IT_FCAT.
CLEAR WA_FCAT.

WA_FCAT-FIELDNAME = 'VTWEG'.
WA_FCAT-TABNAME   = 'IT_FINAL'.
WA_FCAT-SELTEXT_M = 'DIST CHAN'.
APPEND WA_FCAT TO IT_FCAT.
CLEAR WA_FCAT.

WA_FCAT-FIELDNAME = 'SPART'.
WA_FCAT-TABNAME   = 'IT_FINAL'.
WA_FCAT-SELTEXT_M = 'DIV'.
APPEND WA_FCAT TO IT_FCAT.
CLEAR WA_FCAT.


WA_FCAT-FIELDNAME = 'BZIRK'.
WA_FCAT-TABNAME   = 'IT_FINAL'.
WA_FCAT-SELTEXT_M = 'REGION'.
APPEND WA_FCAT TO IT_FCAT.
CLEAR WA_FCAT.

WA_FCAT-FIELDNAME = 'WERKS'.
WA_FCAT-TABNAME   = 'IT_FINAL'.
WA_FCAT-SELTEXT_M = 'PLANT'.
APPEND WA_FCAT TO IT_FCAT.
CLEAR WA_FCAT.

WA_FCAT-FIELDNAME = 'MATNR'.
WA_FCAT-TABNAME   = 'IT_FINAL'.
WA_FCAT-SELTEXT_M = 'MATERIAL'.
WA_FCAT-NO_ZERO   = 'X'.
APPEND WA_FCAT TO IT_FCAT.
CLEAR WA_FCAT.

WA_FCAT-FIELDNAME = 'MAKTX'.
WA_FCAT-TABNAME   = 'IT_FINAL'.
WA_FCAT-SELTEXT_M = 'MATERIAL NAME'.
WA_FCAT-OUTPUTLEN = '20'.
APPEND WA_FCAT TO IT_FCAT.
CLEAR WA_FCAT.

WA_FCAT-FIELDNAME = 'MEINS'.
WA_FCAT-TABNAME   = 'IT_FINAL'.
WA_FCAT-SELTEXT_M = 'UOM'.
APPEND WA_FCAT TO IT_FCAT.
CLEAR WA_FCAT.

WA_FCAT-FIELDNAME = 'EXTWG'.
WA_FCAT-TABNAME   = 'IT_FINAL'.
WA_FCAT-SELTEXT_M = 'MATERIAL GROUP'.
WA_FCAT-OUTPUTLEN = '15'.
APPEND WA_FCAT TO IT_FCAT.
CLEAR WA_FCAT.

WA_FCAT-FIELDNAME = 'LM_FC'.
WA_FCAT-TABNAME   = 'IT_FINAL'.
WA_FCAT-SELTEXT_M = 'LAST MONTH FORECAST'.
WA_FCAT-OUTPUTLEN = '20'.
WA_FCAT-EMPHASIZE = 'C610'.
APPEND WA_FCAT TO IT_FCAT.
CLEAR WA_FCAT.

WA_FCAT-FIELDNAME = 'LM_SA'.
WA_FCAT-TABNAME   = 'IT_FINAL'.
WA_FCAT-SELTEXT_M = 'LAST MONTH SALES'.
WA_FCAT-OUTPUTLEN = '20'.
WA_FCAT-EMPHASIZE = 'C610'.
APPEND WA_FCAT TO IT_FCAT.
CLEAR WA_FCAT.




WA_FCAT-FIELDNAME =  'MONTH1'.
WA_FCAT-TABNAME   =  'IT_FINAL'.
WA_FCAT-SELTEXT_L =  M1_NAME.
WA_FCAT-SELTEXT_M =  M1_NAME.
WA_FCAT-SELTEXT_S =  M1_NAME.
WA_FCAT-DATATYPE  =  'NUMC'.
APPEND WA_FCAT TO IT_FCAT.
CLEAR WA_FCAT.

WA_FCAT-FIELDNAME =  'MONTH2'.
WA_FCAT-TABNAME   =  'IT_FINAL'.
WA_FCAT-SELTEXT_L =  M2_NAME.
WA_FCAT-SELTEXT_M =  M2_NAME.
WA_FCAT-SELTEXT_S =  M2_NAME.
WA_FCAT-DATATYPE    = 'NUMC'.
APPEND WA_FCAT TO IT_FCAT.
CLEAR WA_FCAT.


WA_FCAT-FIELDNAME =  'MONTH3'.
WA_FCAT-TABNAME   = 'IT_FINAL'.
WA_FCAT-SELTEXT_L =  M3_NAME.
WA_FCAT-SELTEXT_M =  M3_NAME.
WA_FCAT-SELTEXT_S =  M3_NAME.
WA_FCAT-DATATYPE    = 'NUMC'.
APPEND WA_FCAT TO IT_FCAT.
CLEAR WA_FCAT.


WA_FCAT-FIELDNAME = 'B_PLAN'.
WA_FCAT-TABNAME   = 'IT_FINAL'.
WA_FCAT-SELTEXT_M =  'BUSINESS PLAN'.
WA_FCAT-OUTPUTLEN = '20'.
APPEND WA_FCAT TO IT_FCAT.
CLEAR WA_FCAT.


WA_FCAT-FIELDNAME = 'Y1M1'.
WA_FCAT-TABNAME   = 'IT_FINAL'.
WA_FCAT-SELTEXT_M =  Y1M1NAME.
WA_FCAT-EMPHASIZE = 'C510'.
APPEND WA_FCAT TO IT_FCAT.
CLEAR WA_FCAT.


WA_FCAT-FIELDNAME = 'Y1M2'.
WA_FCAT-TABNAME   = 'IT_FINAL'.
WA_FCAT-SELTEXT_M =  Y1M2NAME.
WA_FCAT-EMPHASIZE = 'C510'.
APPEND WA_FCAT TO IT_FCAT.
CLEAR WA_FCAT.


WA_FCAT-FIELDNAME = 'Y1M3'.
WA_FCAT-TABNAME   = 'IT_FINAL'.
WA_FCAT-EMPHASIZE = 'C510'.
WA_FCAT-SELTEXT_M =  Y1M3NAME.
APPEND WA_FCAT TO IT_FCAT.
CLEAR WA_FCAT.


WA_FCAT-FIELDNAME = 'Y2M1'.
WA_FCAT-TABNAME   = 'IT_FINAL'.
WA_FCAT-SELTEXT_M =  Y2M1NAME.
WA_FCAT-EMPHASIZE = 'C410'.
APPEND WA_FCAT TO IT_FCAT.
CLEAR WA_FCAT.


WA_FCAT-FIELDNAME = 'Y2M2'.
WA_FCAT-TABNAME   = 'IT_FINAL'.
WA_FCAT-EMPHASIZE = 'C410'.
WA_FCAT-SELTEXT_M = Y2M2NAME.
APPEND WA_FCAT TO IT_FCAT.
CLEAR WA_FCAT.


WA_FCAT-FIELDNAME = 'Y2M3'.
WA_FCAT-EMPHASIZE = 'C410'.
WA_FCAT-SELTEXT_M = Y2M3NAME.
WA_FCAT-TABNAME   = 'IT_FINAL'.
APPEND WA_FCAT TO IT_FCAT.
CLEAR WA_FCAT.


WA_FCAT-FIELDNAME = 'Y3M1'.
WA_FCAT-TABNAME   = 'IT_FINAL'.
WA_FCAT-SELTEXT_M = Y3M1NAME.
WA_FCAT-EMPHASIZE = 'C710'.
APPEND WA_FCAT TO IT_FCAT.
CLEAR WA_FCAT.


WA_FCAT-FIELDNAME = 'Y3M2'.
WA_FCAT-TABNAME   = 'IT_FINAL'.
WA_FCAT-SELTEXT_M =  Y3M2NAME.
WA_FCAT-EMPHASIZE = 'C710'.
APPEND WA_FCAT TO IT_FCAT.
CLEAR WA_FCAT.


WA_FCAT-FIELDNAME = 'Y3M3'.
WA_FCAT-EMPHASIZE = 'C710'.
WA_FCAT-SELTEXT_M = Y3M3NAME.
WA_FCAT-TABNAME   = 'IT_FINAL'.
APPEND WA_FCAT TO IT_FCAT.
CLEAR WA_FCAT.


ENDFORM.


FORM USER_COMMAND USING CODE LIKE SY-UCOMM
                        FIELD TYPE SLIS_SELFIELD.

 IF CODE = '&DATA_SAVE'.

  LOOP AT IT_FINAL INTO WA_FINAL.

  UPDATE ZSD_REG_SALE_FC  FROM WA_FINAL.
  COMMIT WORK AND WAIT.
  CLEAR : WA_FINAL.

  ENDLOOP.


  MESSAGE 'SALES FORECAST PLAN UPDATED SUCESSFULLY' TYPE 'S'.

 ENDIF.
ENDFORM.
