*---------------------------------------------------------------------*
*    generated viewmaintenance function pool
*   generation date: 16.12.2016 at 14:35:08 by user IBM_AMS
*   view maintenance generator version: #001407#
*---------------------------------------------------------------------*
*******************************************************************
*   System-defined Include-files.                                 *
*******************************************************************
  INCLUDE LZMM_PROPOSALTOP.                  " Global Data
  INCLUDE LZMM_PROPOSALUXX.                  " Function Modules

*******************************************************************
*   include-files generated by view maintenance tool              *
*******************************************************************

*      view related include-files   (never change, please)        *
  INCLUDE LZMM_PROPOSALF00                        . " subprograms
  INCLUDE LZMM_PROPOSALI00                        . " PAI modules

*      general include-files        (never change, please)        *
  INCLUDE LSVIMFXX                                . " subprograms
  INCLUDE LSVIMOXX                                . " PBO modules
  INCLUDE LSVIMIXX                                . " PAI modules

*******************************************************************
*   User-defined Include-files (if necessary).                    *
*******************************************************************
* INCLUDE LZMM_PROPOSALF...                  " Subprograms
* INCLUDE LZMM_PROPOSALO...                  " PBO-Modules
* INCLUDE LZMM_PROPOSALI...                  " PAI-Modules
