*---------------------------------------------------------------------*
*    generated viewmaintenance function pool
*   generation date: 09.08.2010 at 18:36:54 by user IBMABAP01
*   view maintenance generator version: #001407#
*---------------------------------------------------------------------*
*******************************************************************
*   System-defined Include-files.                                 *
*******************************************************************
  INCLUDE LZUSERIDTOP.                       " Global Data
  INCLUDE LZUSERIDUXX.                       " Function Modules

*******************************************************************
*   include-files generated by view maintenance tool              *
*******************************************************************

*      view related include-files   (never change, please)        *
  INCLUDE LZUSERIDF00                             . " subprograms
  INCLUDE LZUSERIDI00                             . " PAI modules

*      general include-files        (never change, please)        *
  INCLUDE LSVIMFXX                                . " subprograms
  INCLUDE LSVIMOXX                                . " PBO modules
  INCLUDE LSVIMIXX                                . " PAI modules

*******************************************************************
*   User-defined Include-files (if necessary).                    *
*******************************************************************
* INCLUDE LZUSERIDF...                       " Subprograms
* INCLUDE LZUSERIDO...                       " PBO-Modules
* INCLUDE LZUSERIDI...                       " PAI-Modules
